default: &default
  database: dictionary
  host: localhost
  adapter: mysql2
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
